kind: Service
apiVersion: v1
metadata:
  name: tcp-loadbalancer-cicd
  namespace: gitlab-managed-apps
spec:
  type: LoadBalancer
  selector: #Manda el trafico a los pods que posean este etiqueta
    app: appcicd #QUe seria el ingress
  ports:
    - name: http
      protocol: TCP
      port: 80 
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443 
      targetPort: 443
 