apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otium-wp-mysql-pvc
#  namespace: webpages
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otium-wp-pvc
#  namespace: webpages
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage

#OSTICKET
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otium-osticket-pvc
#  namespace: webpages
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: otium-osticket-mysql-pvc
#  namespace: webpages
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: do-block-storage



