apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNREF6TVRBeApNelF6TXpGYUZ3MDBNREF6TVRBeE16UXpNekZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFDZTNSZ0lnNHVSak9RTnJoWjZvVThBZktRNHpDblR0TUs3ZmVVKy9LTG1OQXkzcEZkbgpCcE50cFZBYTg4TDlGSEJNU0kyS3BHMmpyeG1JUVZ4cHBrQzg4M2RZSUZCZXN0NERFRDFMd29nMDA2ZFZqbHB2ClV3VkgyQmpDU2p3R3lsMnRpM2JXWGZ3VHRKWmE4Zmk2Y0JDU1VKYlpQTHpFVTQxd0t1dlVkam0yak9CS1JRdkwKSUx2dGhmSWhxbHB3K1NUbEwreENVRUZkYXJRd2JaRzcrbVBybVU2RHd0YzdQYzV4d0JhaWVpa1hVdE5KRmF5TgpKMHBNUnRyQlVpYVQyaGtTTFZEQnh3c0l3d1B2c0s5T01nNGVDNjRqR2xsZmlPNGFZRHRaRmNyU0xKblZITWJICkxzQVZkOHdYUERjZ0dNbEMrZGNrV2VhbFplbERSNEo4c0xHQkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlFHMzR6VW1sdU02WjRyWlBxRAp5d0ljQkJXOVhEQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFPMmtZT3BlN2IzcUcyN2lyalM0azRvb3RydklICk5oZ2VxRWsrbE9mQ1ZaY09lSnJTaldCYU9NWXRSeWNpM24rQUhvZHVLRmZndFkvYnhkZzRFR2lHbnRkV1lXU1EKeWxmeG5LeFg1S1I5bHgzVjlQTUR5YnhNU3UzNGZGRE9TbWh1bk1HaVFtNS9naVVMRmQ4WGlWbmZpVmxFN0JoVwphVzR0T0lVTENxekhqbmVDeEZmZE5GUCtQcjhQTHhNMUdWTHhFQUZhcExKSWZzcktpNm1kbkswQUdvOEJWSWlUCjAyekNlQ2UvamE5bEc2cXh2cEFlSEZmZVBoWVRsYVhwNFFQbFBTS2Z2eXF5MHlFcGN1QTlFS1JIcjJ4WWN2bzMKM0xnWm9wVXZTKzYza2xQN0NZQjhLR0p1NmgvL2s4NmZsSVRTRDBxcFVqWFRYTHc0dWw0NjQvcm42UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://74e21784-a437-4090-8133-4c4aea770d12.k8s.ondigitalocean.com
  name: do-nyc1-cicd
contexts:
- context:
    cluster: do-nyc1-cicd
    user: do-nyc1-cicd-admin
  name: do-nyc1-cicd
current-context: do-nyc1-cicd
users:
- name: do-nyc1-cicd-admin
  user:
    token: 5a9b67cb1784373826c0fbe226da27ab4cba2ce745db150cf213fea4b5da127c
