apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  type: NodePort
  ports:
    - protocol: TCP
      name: web
      port: 8000  #Puerto expuesto , recibe desde el load balancer (creo desde el pod de traefik ) . Llega y lo manda al 8000 (targetPort) del nodo
      targetPort: 8000
      nodePort: 30080 #Puerto del contenedor
    - protocol: TCP
      name: admin
      targetPort: 8080
      port: 8080
    - protocol: TCP
      name: websecure
      port: 4443  #Puerto expuesto , recibe desde el load balancer. Llega y lo manda al 4443 (targetPort) del nodo
      targetPort: 4443
      nodePort: 30443 #Puerto del contenedor

  selector:
    app: traefik #Le manda el trafico a los pods que tengan esta etiqueta

---
##Servicio demo. Aqui deberia ir la aplicacion
##Servicio para el WOrdpress
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress #Buscara los replications controlers, que posean esta etiquita
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80 #Ip que tendra el contenedor expuesto
  selector:
    app: wordpress
    tier: frontend

---
##Servicio para el WOrdpress2
apiVersion: v1
kind: Service
metadata:
  name: wordpress2
  labels:
    app: wordpress2 #Buscara los replications controlers, que posean esta etiquita
spec:
  ports:
    - protocol: TCP
      name: web
      port: 80 #Ip que tendra el contenedor expuesto
  selector:
    app: wordpress2
    tier: frontend